ktor:
  application:
    modules:
      - com.aatech.module.MainModuleKt.mainModule
      - com.aatech.module.MySqlModuleKt.mySqlModule
      - com.aatech.module.MondoDbModuleKt.mondoDbModule
  deployment:
    port: 8080
