name: Deploy to DigitalOcean
on:
  workflow_dispatch:   # 👈 manual trigger
  # push:              # 👈 keep this if you ALSO want auto-deploy on push
  #   branches: ["main"]

obs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H your.server.com >> ~/.ssh/known_hosts

      - name: Connect & Run Commands
        run: |
          ssh -o StrictHostKeyChecking=no root@139.59.24.34 "echo 'Connected via GitHub Actions!' && whoami && hostname"
          
