name: Deploy to DigitalOcean
on:
  workflow_dispatch:   # 👈 manual trigger
  # push:              # 👈 keep this if you ALSO want auto-deploy on push
  #   branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run SSH commands on DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 139.59.24.34
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Connected to DigitalOcean!"
            cd BetweenUsServer/
            ls -la
            # Add your deployment commands here
            # git pull origin main
            # npm install
            # pm2 restart your-app
