name: Deploy to DigitalOcean 🚀

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        description: "Choose deployment type"
        required: true
        default: "build"
        type: choice
        options:
          - build
          - clean
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (contains(github.event.head_commit.message, '[deploy]') || contains(github.event.head_commit.message, '[build]')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_type == 'build')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SSH commands on DigitalOcean
        id: deploy_step
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "✅ Connected to DigitalOcean!"
            cd BetweenUsServer/
            echo "📦 Pulling latest code..."
            docker compose down 
            git pull origin master
            docker compose up --build -d
            echo "✅ Deployment Finished"

            echo "📊 Gathering System Info..."
            echo "---- Disk Usage ----"
            df -h
            echo "---- Memory Usage ----"
            free -m
            echo "---- CPU Load ----"
            uptime
            echo "---- Top Processes ----"
            ps aux --sort=-%mem | head -n 10
            echo "---- Docker Status ----"
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
            echo "---- Last 20 Logs ----"
            docker compose logs --tail=20

  clean_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[clean]') || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_type == 'clean')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SSH commands on DigitalOcean
        id: clean_step
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "✅ Connected to DigitalOcean!"
            cd BetweenUsServer/
            echo "🧹 Performing clean deployment..."
            docker compose down --rmi all --volumes
            git pull origin master
            docker compose up --build -d
            echo "✅ Clean Deployment Finished"

            echo "📊 Gathering System Info..."
            echo "---- Disk Usage ----"
            df -h
            echo "---- Memory Usage ----"
            free -m
            echo "---- CPU Load ----"
            uptime
            echo "---- Top Processes ----"
            ps aux --sort=-%mem | head -n 10
            echo "---- Docker Status ----"
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
            echo "---- Last 20 Logs ----"
            docker compose logs --tail=20

  report:
    runs-on: ubuntu-latest
    needs: [deploy, clean_deploy]
    if: always()
    steps:
      - name: Deployment Report
        run: |
          echo "📢 Deployment Report"
          echo "---------------------"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Commit: $GITHUB_SHA"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Triggered by: $GITHUB_ACTOR"
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Deploy Type: ${{ github.event.inputs.deploy_type }}"
          else
            if echo "${{ github.event.head_commit.message }}" | grep -q "\[clean\]"; then
              echo "Deploy Type: clean"
            else
              echo "Deploy Type: build"
            fi
          fi

          echo "---------------------"
          echo "🔎 Job Results"
          echo "Deploy Job: ${{ needs.deploy.result }}"
          echo "Clean Deploy Job: ${{ needs.clean_deploy.result }}"

          if [ "${{ needs.deploy.result }}" == "success" ] || [ "${{ needs.clean_deploy.result }}" == "success" ]; then
            echo "✅ Deployment Successful!"
          else
            echo "❌ Deployment Failed!"
          fi
